# Generated by Django 6.0.7 on 2026-08-11 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuarios.aprendiz'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='eventos.inscripcion'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('evento', 'aprendiz')},
        ),
    ]
