# Generated by Django 6.0.7 on 2026-08-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('inscrito', 'Inscrito'), ('asistio', 'Asistió'), ('no_asistio', 'No asistió'), ('cancelada', 'Cancelada')], default='inscrito', max_length=20),
        ),
    ]
