# Generated by Django 6.0.7 on 2026-08-20 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_estado_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
