"""
Django settings for betime project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-us62#!r_4+cia^qe)vop+r93l0^r*6u9h$e%uzqk0j+vefn-_u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tables2',
    'django_filters',
    # Registro carpeta core
    'core',
    'usuarios',
    'eventos',
    'bienestar',
    'publicaciones',
    'notificaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'betime.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # RUTA PARA QUE PYTHON SEPA DONDE ESTA TEMPLATES (VISTAS HTML)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'betime.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'betime',
        'USER': 'postgres',
        'PASSWORD': 'betime123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# django-tables2: usa el estilo Bootstrap 5 en todas las tablas por
# defecto, para no tener que repetirlo en cada Table.Meta.
DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"


# Archivos subidos por los usuarios (imágenes de publicaciones, etc.)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / "media"

AUTH_USER_MODEL = "usuarios.Usuario"


# Autenticación
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

LOGIN_URL = "usuarios:login"

LOGIN_REDIRECT_URL = "usuarios:dashboard"

LOGOUT_REDIRECT_URL = "index"


# Mensajes (para que coincidan con las clases de alerta de Bootstrap)
# https://docs.djangoproject.com/en/6.0/ref/contrib/messages/

from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.ERROR: "danger",
}


# Correo (para el restablecimiento de contraseña)
# En desarrollo los correos se imprimen en la consola.
# En producción se debe configurar un backend SMTP real.

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "betimesena2026@gmail.com"
EMAIL_HOST_PASSWORD = "nalhryykzpbziviq"
DEFAULT_FROM_EMAIL = "Be Time <betimesena@gmail.com>"