# Generated by Django 6.0.7 on 2026-08-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(default='solicitada', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asesoría',
                'verbose_name_plural': 'Asesorías',
            },
        ),
        migrations.CreateModel(
            name='HorasBienestar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_horas', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Horas de Bienestar',
                'verbose_name_plural': 'Horas de Bienestar',
            },
        ),
    ]
