# Generated by Django 6.0.7 on 2026-08-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20),
        ),
    ]
