# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0003_alter_asesoria_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroBienestar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bienestar/equipo/')),
                ('correo_asesorias', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro de Bienestar',
                'verbose_name_plural': 'Miembros de Bienestar',
                'ordering': ['nombre'],
            },
        ),
    ]
