# Generated by Django 6.0.7 on 2026-08-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_rol_alter_aprendiz_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('egresado', 'Egresado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada')], default='activa', max_length=20),
        ),
    ]
