# Generated by Django 6.0.7 on 2026-08-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20),
        ),
    ]
